import { StyleSheet } from "react-native";

export const screenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#EEF4FF",
  },
  backgroundTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 360,
    backgroundColor: "#0F172A",
    borderBottomLeftRadius: 44,
    borderBottomRightRadius: 44,
  },
  backgroundCircleOne: {
    position: "absolute",
    top: 90,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 180,
    backgroundColor: "rgba(29,78,216,0.24)",
  },
  backgroundCircleTwo: {
    position: "absolute",
    top: 240,
    left: -60,
    width: 180,
    height: 180,
    borderRadius: 180,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  scrollWrap: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.98)",
    borderRadius: 32,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.18)",
    shadowColor: "#020617",
    shadowOpacity: 0.12,
    shadowRadius: 26,
    shadowOffset: {
      width: 0,
      height: 14,
    },
    elevation: 10,
  },
  cardTablet: {
    alignSelf: "center",
    width: 560,
    padding: 30,
  },
});

export const heroStyles = StyleSheet.create({
  wrapper: {
    alignItems: "center",
  },
  wrapperTablet: {
    paddingTop: 10,
  },
  logoBadge: {
    marginTop: 8,
    marginBottom: 14,
  },
  logoCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#1D4ED8",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#1D4ED8",
    shadowOpacity: 0.3,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 8,
  },
  heroTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#DBEAFE",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    marginBottom: 10,
  },
  heroTagText: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  brand: {
    fontSize: 13,
    fontWeight: "900",
    color: "#1D4ED8",
    letterSpacing: 1.4,
  },
  title: {
    marginTop: 10,
    fontSize: 30,
    fontWeight: "900",
    color: "#0F172A",
    textAlign: "center",
  },
  iconRow: {
    marginTop: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  featureIcon: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: "#EFF6FF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#DBEAFE",
  },
  featureIconCenter: {
    width: 66,
    height: 66,
    borderRadius: 22,
    backgroundColor: "#1D4ED8",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#1D4ED8",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 6,
  },
  otpHeaderWrap: {
    width: "100%",
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 8,
  },
  verifyTopIcon: {
    width: 64,
    height: 64,
    borderRadius: 22,
    backgroundColor: "#EFF6FF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    shadowColor: "#1D4ED8",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 3,
  },
  otpTitle: {
    marginTop: 14,
    fontSize: 24,
    fontWeight: "900",
    color: "#0F172A",
    textAlign: "center",
  },
});

export const formStyles = StyleSheet.create({
  formWrap: {
    marginTop: 22,
    gap: 16,
  },
  fieldGroup: {
    gap: 10,
  },
  label: {
    fontSize: 14,
    fontWeight: "800",
    color: "#334155",
  },
  inputWrap: {
    height: 58,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#DBEAFE",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  countryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    height: 38,
    borderRadius: 999,
    backgroundColor: "#E2E8F0",
  },
  countryFlag: {
    fontSize: 14,
    lineHeight: 16,
  },
  countryText: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
  phoneInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
    letterSpacing: 0.6,
  },
  button: {
    marginTop: 8,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#1D4ED8",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#1D4ED8",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 6,
  },
  buttonPressed: {
    transform: [{ scale: 0.985 }],
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  buttonLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  otpHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  otpGrid: {
    flexDirection: "row",
    gap: 10,
  },
  otpBox: {
    flex: 1,
    height: 58,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    backgroundColor: "#F8FAFC",
    color: "#0F172A",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    paddingVertical: 0,
  },
  otpBoxFilled: {
    backgroundColor: "#EFF6FF",
    borderColor: "#1D4ED8",
  },
  inlineLink: {
    color: "#1D4ED8",
    fontSize: 13,
    fontWeight: "800",
  },
  linkText: {
    textAlign: "center",
    color: "#1D4ED8",
    fontSize: 14,
    fontWeight: "800",
  },
  linkTextDisabled: {
    color: "#94A3B8",
  },
  changeText: {
    textAlign: "center",
    color: "#64748B",
    fontSize: 13,
    fontWeight: "700",
  },
  secondaryActions: {
    gap: 10,
    marginTop: 2,
  },
});
