import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SHADOWS, SPACING, TYPOGRAPHY } from "@/src/theme";

const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: COLORS.background,
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  container: {
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
  },
  center: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  heroCard: {
    ...SHADOWS.soft,
    borderRadius: 28,
    marginBottom: SPACING.md,
    overflow: "hidden",
    padding: SPACING.md,
  },
  heroTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  badge: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(15, 23, 42, 0.28)",
    borderRadius: 999,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
  },
  badgeText: {
    color: COLORS.textInverse,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  progressPill: {
    alignItems: "flex-end",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 999,
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
  },
  progressLabel: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  progressValue: {
    color: COLORS.textInverse,
    fontSize: 15,
    fontWeight: "800",
  },
  heroBody: {
    alignItems: "center",
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: SPACING.md,
  },
  avatarWrap: {
    height: 92,
    width: 92,
  },
  avatar: {
    borderRadius: 46,
    height: 92,
    width: 92,
  },
  avatarFallback: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 46,
    height: 92,
    justifyContent: "center",
    width: 92,
  },
  avatarFallbackText: {
    color: COLORS.primaryDark,
    fontSize: 28,
    fontWeight: "900",
  },
  avatarEditBadge: {
    alignItems: "center",
    backgroundColor: COLORS.primarySoft,
    borderColor: "rgba(255,255,255,0.9)",
    borderRadius: 999,
    borderWidth: 2,
    bottom: 0,
    height: 28,
    justifyContent: "center",
    position: "absolute",
    right: 0,
    width: 28,
  },
  heroTextWrap: {
    flex: 1,
  },
  titleLight: {
    ...TYPOGRAPHY.title,
    color: COLORS.textInverse,
  },
  subtitleLight: {
    color: "rgba(248,250,252,0.86)",
    lineHeight: 19,
    marginTop: 4,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: SPACING.sm,
  },
  metaChip: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.26)",
    borderRadius: 999,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 7,
  },
  metaText: {
    color: COLORS.textInverse,
    fontSize: 12,
    fontWeight: "700",
  },
  uploadButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: RADIUS.full,
    flexDirection: "row",
    gap: 8,
    marginTop: SPACING.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  uploadText: {
    color: COLORS.primaryDark,
    fontSize: 13,
    fontWeight: "800",
  },
  photoHint: {
    color: "rgba(248,250,252,0.82)",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
  },
  card: {
    ...SHADOWS.soft,
    backgroundColor: COLORS.card,
    borderColor: COLORS.border,
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: SPACING.md,
    padding: SPACING.md,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: SPACING.sm,
  },
  sectionIcon: {
    alignItems: "center",
    backgroundColor: COLORS.primarySoft,
    borderRadius: 14,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  sectionTextWrap: {
    flex: 1,
    marginLeft: SPACING.sm,
  },
  sectionTitle: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  sectionSubtitle: {
    color: COLORS.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 2,
  },
  dualRow: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  inputShell: {
    backgroundColor: COLORS.cardMuted,
    borderColor: COLORS.border,
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    marginTop: SPACING.sm,
    minHeight: 52,
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
  },
  inputIcon: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    width: 20,
  },
  input: {
    color: COLORS.textPrimary,
    flex: 1,
    fontSize: 14,
    minHeight: 36,
    padding: 0,
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: "top",
  },
  footerNote: {
    alignItems: "center",
    backgroundColor: COLORS.primarySoft,
    borderRadius: 18,
    flexDirection: "row",
    gap: 8,
    marginBottom: SPACING.md,
    padding: SPACING.sm,
  },
  footerNoteText: {
    color: COLORS.textPrimary,
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
  },
  footer: {
    backgroundColor: "rgba(234,241,255,0.96)",
    borderTopColor: "rgba(191,219,254,0.75)",
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.sm,
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
});

export default styles;
